### ISSUE TITLE
Project Compatibility for Xcode 8.2.1 (10.11.6)

### ISSUE THREAD

**Issue by badruzeus** [syscl/CPUTune#1]
Hello, nice project @syscl 
Anyway, could you make it becomes compatible with Xcode8 clang?

`Failed to load project at '~/CPUTune/CPUTune.xcodeproj', incompatible project version.`

Thanks.

**Comment by syscl** [comment]
Sure, yes, I will.

**Comment by syscl** [comment]
@badruzeus Please try the latest the version and report back.Thanks.
