### ISSUE TITLE
Stop Working after update Mac os

### ISSUE THREAD

**Issue by parth0072** [syscl/CPUTune#13]
I Have updated my mac Catalina 10.15.5 to 10.15.6 and CPUTune kext stop working.
I have followed this step again but still the same result.
it stop loading kext on startup. 
i have put kext in /Library/Extension
https://portugnole.blogspot.com/2020/05/running-macbook-without-battery-lets-go.html

**Comment by syscl** [comment]
Hi @parth0072 , could you provide a little bit more context about the issue? Thanks!

**Comment by parth0072** [comment]
Sure.
But i tried that step few times again and its looks like it is working fine now.

Thanks
