### ISSUE TITLE
Kernal panic....not booting up...

### ISSUE THREAD

**Issue by codenamenam** [syscl/CPUTune#19]
![0A53F76E-0350-4F8D-9507-22014AAC9C79](https://user-images.githubusercontent.com/54799053/91045625-21fa9b00-e652-11ea-83ab-e4e20d0a4b3b.jpeg)
What should I do? I can't boot up. Apple logo with no progress bar. Recovery mode is ok but reinstalling the mac os doesn't work. Please help me.....

**Comment by syscl** [comment]
I think the version you are using is too old: v2.0.2. Feel free to use the latest one and report.
