### ISSUE TITLE
Unable to compile for proper running on Mojave

### ISSUE THREAD

**Issue by gymnae** [syscl/CPUTune#2]
I cloned this repository, opened the project file in xCode and pressed "Build". The kext appeared in the derived folder under build -> product -> debug.

I attempted to run it manually via kextload and by placing it into the "Other" folder of Clover kexts. The kext won't load, neither manually nor by clover

Am I missing something? I am lacking experience with xCode I have to admit.

**Comment by gymnae** [comment]
Fixed it by installing the Mojave 10.14 SDK, because newer xCode version don't bring this along.

**Comment by syscl** [comment]
@Gymnae feel free to try the latest version which bring back a lot of improvements and optimization :)
