### ISSUE TITLE
for syscl

### ISSUE THREAD

**Issue by christophe-duc** [syscl/CPUTune#7]
Hi, sorry don't know how to contact you directly to have a chat :)

I am still trying to understand why Turboboost needs to be off when battery is out, and I have analyzed some of the IOPlatformPlugins and especially X86PlatformShim, where I think the problem is coming from.

Would you be able to share what you see from the IOReg with a battery and turboboost disabled for the following keys (they are under the X86PlatformPlugin)?

<img width="466" alt="Screen Shot 2020-06-03 at 16 30 21" src="https://user-images.githubusercontent.com/20467671/83681121-5103f200-a5b8-11ea-8b3c-080b23a862df.png">

Thanks

**Comment by syscl** [comment]
@christophe-duc tldr, just saw this message. Are you still in need of my ioreg? I can try to attach it here

**Comment by christophe-duc** [comment]
If you have time, it would be great.

I am thinking of creating a slack or discord so we can talk more interactively, any preference for you?

**Comment by syscl** [comment]
@christophe-duc slack sounds good to me :)

**Comment by syscl** [comment]
@christophe-duc here's the info with turbo disabled with battery
![image](https://user-images.githubusercontent.com/11594858/84325017-b747c200-ab2e-11ea-983c-0a8bd1a64fb7.png)

here's the running log
```
CPUInfo:47: cpu model: 0x9e, supported HWP, number of cores: 6, turbo ratio limit permission: RW
DEBUG getProperty:68: cpu-tune-panic not existed in NVRAM property
init:64: Update time interval 1000 ms per cycle
init:67: succeeded!
disableTurboBoost:288: change 0x850089 to 0x4000850089 in MSR_IA32_MISC_ENABLE(0x1a0)
disableProcHot:299: change 0x64005f to 0x64005e in MSR_IA32_POWERCTL(0x1fc)
enableSpeedShift:322: 0x1 in MSR_IA32_PM_ENABLE(0x770) remains the same
start:152: registerService
stop:349: restore MSR_IA32_POWER_CTK from 0x64005e to 0x64005f
stop:353: restore MSR_IA32_MISC_ENABLE from 0x4000850089 to 0x850089
stop:362: restore MSR_IA32_PM_ENABLE from 0x1 to 0x0
```
